/**
 * WIZARD NES - Movie & Content Data
 * Classic cartoons from Internet Archive + YouTube NES content
 */

'use strict';

const MoviesData = {

  /* ---- Classic Public Domain Cartoons from Internet Archive ---- */
  cartoons: [
    // Betty Boop Collection
    {
      id: 'betty_1',
      title: 'Betty Boop: Minnie the Moocher',
      category: 'betty-boop',
      year: 1932,
      duration: '7:27',
      description: 'Betty Boop and Bimbo are chased by a walrus ghost. Features Cab Calloway.',
      thumbnail: 'https://archive.org/services/img/MinnietheMoocher',
      embedUrl: 'https://archive.org/embed/MinnietheMoocher',
      archiveId: 'MinnietheMoocher',
      points: 50,
      tags: ['betty boop', 'classic', 'fleischer', 'jazz'],
    },
    {
      id: 'betty_2',
      title: 'Betty Boop: Snow White',
      category: 'betty-boop',
      year: 1933,
      duration: '6:45',
      description: 'Betty Boop stars in this classic Fleischer Studios adaptation of Snow White.',
      thumbnail: 'https://archive.org/services/img/SnowWhite1933',
      embedUrl: 'https://archive.org/embed/SnowWhite1933',
      archiveId: 'SnowWhite1933',
      points: 50,
      tags: ['betty boop', 'fleischer', 'fairy tale'],
    },
    {
      id: 'betty_3',
      title: 'Betty Boop: Popeye the Sailor',
      category: 'betty-boop',
      year: 1933,
      duration: '7:05',
      description: "Popeye's first screen appearance alongside Betty Boop.",
      thumbnail: 'https://archive.org/services/img/PopeyetheSailor1933',
      embedUrl: 'https://archive.org/embed/PopeyetheSailor1933',
      archiveId: 'PopeyetheSailor1933',
      points: 55,
      tags: ['betty boop', 'popeye', 'fleischer', 'premiere'],
    },

    // Felix the Cat
    {
      id: 'felix_1',
      title: 'Felix the Cat: Felix in Hollywood',
      category: 'felix-cat',
      year: 1923,
      duration: '5:30',
      description: "Felix visits Hollywood and encounters many classic film stars.",
      thumbnail: 'https://archive.org/services/img/FelixinHollywood',
      embedUrl: 'https://archive.org/embed/FelixinHollywood',
      archiveId: 'FelixinHollywood',
      points: 45,
      tags: ['felix the cat', 'silent film', 'classic', 'hollywood'],
    },
    {
      id: 'felix_2',
      title: 'Felix the Cat: Felix Woos Whoopee',
      category: 'felix-cat',
      year: 1929,
      duration: '6:15',
      description: 'A classic Felix the Cat cartoon adventure.',
      thumbnail: 'https://archive.org/services/img/FelixWoosWhoopee',
      embedUrl: 'https://archive.org/embed/FelixWoosWhoopee',
      archiveId: 'FelixWoosWhoopee',
      points: 45,
      tags: ['felix the cat', 'silent', 'classic'],
    },

    // Popeye
    {
      id: 'popeye_1',
      title: 'Popeye: Blow Me Down!',
      category: 'popeye',
      year: 1934,
      duration: '7:30',
      description: 'Popeye the Sailor in one of his classic adventures in a Mexican town.',
      thumbnail: 'https://archive.org/services/img/BlowMeDown1934',
      embedUrl: 'https://archive.org/embed/BlowMeDown1934',
      archiveId: 'BlowMeDown1934',
      points: 55,
      tags: ['popeye', 'fleischer', 'sailor', 'classic'],
    },
    {
      id: 'popeye_2',
      title: "Popeye: Fleischer's Color Special",
      category: 'popeye',
      year: 1936,
      duration: '16:38',
      description: "Popeye the Sailor Meets Sindbad the Sailor - one of Fleischer's early color specials.",
      thumbnail: 'https://archive.org/services/img/PopeyeSindbad1936',
      embedUrl: 'https://archive.org/embed/PopeyeSindbad1936',
      archiveId: 'PopeyeSindbad1936',
      points: 80,
      tags: ['popeye', 'fleischer', 'color', 'sindbad'],
    },

    // Woody Woodpecker
    {
      id: 'woody_1',
      title: 'Woody Woodpecker: Knock Knock',
      category: 'woody-woodpecker',
      year: 1940,
      duration: '6:45',
      description: "Woody Woodpecker's first screen appearance, directed by Walter Lantz.",
      thumbnail: 'https://archive.org/services/img/WoodyWoodpeckerKnockKnock',
      embedUrl: 'https://archive.org/embed/WoodyWoodpeckerKnockKnock',
      archiveId: 'WoodyWoodpeckerKnockKnock',
      points: 60,
      tags: ['woody woodpecker', 'lantz', 'premiere', 'classic'],
    },

    // Bugs Bunny / Looney Tunes (Public Domain)
    {
      id: 'bugs_1',
      title: "Bugs Bunny: Any Bonds Today?",
      category: 'looney-tunes',
      year: 1942,
      duration: '3:00',
      description: "Bugs Bunny promotes war bonds in this patriotic Warner Bros. short.",
      thumbnail: 'https://archive.org/services/img/bugs_bunny_1942_any_bonds_today',
      embedUrl: 'https://archive.org/embed/bugs_bunny_1942_any_bonds_today',
      archiveId: 'bugs_bunny_1942_any_bonds_today',
      points: 40,
      tags: ['bugs bunny', 'looney tunes', 'warner bros', 'ww2'],
    },

    // Superman (Fleischer/Famous Studios)
    {
      id: 'superman_1',
      title: 'Superman: The Mad Scientist',
      category: 'superman',
      year: 1941,
      duration: '10:00',
      description: "Superman's first animated appearance, battling a mad scientist threatening Metropolis.",
      thumbnail: 'https://archive.org/services/img/superman_1941_01_the_mad_scientist',
      embedUrl: 'https://archive.org/embed/superman_1941_01_the_mad_scientist',
      archiveId: 'superman_1941_01_the_mad_scientist',
      points: 70,
      tags: ['superman', 'fleischer', 'dc', 'superhero', 'premiere'],
    },
    {
      id: 'superman_2',
      title: 'Superman: The Mechanical Monsters',
      category: 'superman',
      year: 1941,
      duration: '9:43',
      description: 'Superman battles giant robots terrorizing the city.',
      thumbnail: 'https://archive.org/services/img/superman_mechanical_monsters',
      embedUrl: 'https://archive.org/embed/superman_mechanical_monsters',
      archiveId: 'superman_mechanical_monsters',
      points: 70,
      tags: ['superman', 'fleischer', 'robots', 'action'],
    },
    {
      id: 'superman_3',
      title: 'Superman: Billion Dollar Limited',
      category: 'superman',
      year: 1942,
      duration: '8:35',
      description: 'Superman foils a train robbery.',
      thumbnail: 'https://archive.org/services/img/SupermanBillionDollarLimited',
      embedUrl: 'https://archive.org/embed/SupermanBillionDollarLimited',
      archiveId: 'SupermanBillionDollarLimited',
      points: 65,
      tags: ['superman', 'fleischer', 'train', 'action'],
    },
    {
      id: 'superman_4',
      title: 'Superman: The Arctic Giant',
      category: 'superman',
      year: 1942,
      duration: '7:58',
      description: 'Superman battles a giant dinosaur thawed from Arctic ice.',
      thumbnail: 'https://archive.org/services/img/Superman-ArcticGiant',
      embedUrl: 'https://archive.org/embed/Superman-ArcticGiant',
      archiveId: 'Superman-ArcticGiant',
      points: 65,
      tags: ['superman', 'fleischer', 'dinosaur', 'action'],
    },

    // Popeye Color Classics
    {
      id: 'popeye_3',
      title: 'Popeye: Wotta Nitemare',
      category: 'popeye',
      year: 1939,
      duration: '6:52',
      description: "Popeye has a nightmare about Ali Baba's Arabian Nights.",
      thumbnail: 'https://archive.org/services/img/WottaNitemare',
      embedUrl: 'https://archive.org/embed/WottaNitemare',
      archiveId: 'WottaNitemare',
      points: 55,
      tags: ['popeye', 'fleischer', 'dream', 'classic'],
    },

    // Betty Boop additional
    {
      id: 'betty_4',
      title: "Betty Boop's Penthouse",
      category: 'betty-boop',
      year: 1933,
      duration: '6:15',
      description: "Betty Boop and her friends in a classic Fleischer Studios cartoon.",
      thumbnail: 'https://archive.org/services/img/BettyBoopin_Penthouse',
      embedUrl: 'https://archive.org/embed/BettyBoopin_Penthouse',
      archiveId: 'BettyBoopin_Penthouse',
      points: 50,
      tags: ['betty boop', 'fleischer', 'classic'],
    },

    // Ghostly Cartoons
    {
      id: 'casper_1',
      title: 'Casper the Friendly Ghost: There\'s Good Boos Tonight',
      category: 'casper',
      year: 1948,
      duration: '7:15',
      description: "Casper befriends a fox. One of the earliest Casper cartoons.",
      thumbnail: 'https://archive.org/services/img/CasperGoodBoos',
      embedUrl: 'https://archive.org/embed/CasperGoodBoos',
      archiveId: 'CasperGoodBoos',
      points: 55,
      tags: ['casper', 'paramount', 'friendly ghost', 'classic'],
    },

    // Mighty Mouse
    {
      id: 'mighty_1',
      title: 'Mighty Mouse: The Lion and the Mouse',
      category: 'mighty-mouse',
      year: 1947,
      duration: '6:30',
      description: 'Mighty Mouse saves animals from a cruel lion.',
      thumbnail: 'https://archive.org/services/img/MightyMouseLionMouse',
      embedUrl: 'https://archive.org/embed/MightyMouseLionMouse',
      archiveId: 'MightyMouseLionMouse',
      points: 55,
      tags: ['mighty mouse', 'terrytoons', 'classic', 'superhero'],
    },
  ],

  /* ---- NES Content on YouTube ---- */
  nesVideos: [
    {
      id: 'nes_yt_1',
      title: 'NES Classic Games Compilation',
      category: 'nes-gameplay',
      description: 'Best moments from classic NES games including Mario, Zelda, Mega Man and more!',
      youtubeId: 'alv4T0oRQOE',
      duration: '10:30',
      points: 30,
      tags: ['nes', 'classic', 'gameplay', 'compilation'],
    },
    {
      id: 'nes_yt_2',
      title: 'Top 100 NES Games of All Time',
      category: 'nes-review',
      description: 'A comprehensive ranking of the greatest NES games ever made.',
      youtubeId: 'PY4BEeAL3HU',
      duration: '42:00',
      points: 60,
      tags: ['nes', 'top 100', 'ranking', 'review'],
    },
    {
      id: 'nes_yt_3',
      title: 'Super Mario Bros Speed Run World Record',
      category: 'nes-speedrun',
      description: 'Watch the fastest Super Mario Bros NES speed run.',
      youtubeId: '7S_pzVXvxzc',
      duration: '4:55',
      points: 40,
      tags: ['mario', 'speedrun', 'world record', 'nes'],
    },
    {
      id: 'nes_yt_4',
      title: 'Legend of Zelda Original NES Complete Walkthrough',
      category: 'nes-walkthrough',
      description: 'Full walkthrough of the original Legend of Zelda for NES.',
      youtubeId: 'Zqs3QnXqBKE',
      duration: '1:45:00',
      points: 100,
      tags: ['zelda', 'walkthrough', 'nes', 'complete'],
    },
    {
      id: 'nes_yt_5',
      title: 'NES Classic Mini All Games Shown',
      category: 'nes-review',
      description: 'Every game on the NES Classic Mini demonstrated.',
      youtubeId: 'bq-bByRqkgI',
      duration: '45:20',
      points: 65,
      tags: ['nes classic mini', 'review', 'all games'],
    },
    {
      id: 'nes_yt_6',
      title: 'Contra NES - Full Playthrough No Konami Code',
      category: 'nes-gameplay',
      description: 'Complete Contra playthrough without using the famous Konami code.',
      youtubeId: 'xSYFoVl1YLI',
      duration: '18:45',
      points: 50,
      tags: ['contra', 'nes', 'playthrough', 'no cheat'],
    },
    {
      id: 'nes_yt_7',
      title: 'Mega Man 2 Perfect Run - NES Classic',
      category: 'nes-speedrun',
      description: 'Perfect playthrough of Mega Man 2 for NES.',
      youtubeId: 'Qfx5tERlJEo',
      duration: '35:00',
      points: 55,
      tags: ['mega man', 'nes', 'perfect', 'speedrun'],
    },
    {
      id: 'nes_yt_8',
      title: 'History of the NES - Nintendo Entertainment System Documentary',
      category: 'nes-history',
      description: 'The complete history of the Nintendo Entertainment System and its impact on gaming.',
      youtubeId: 'X6M2LgSaF4g',
      duration: '30:00',
      points: 45,
      tags: ['nes', 'history', 'nintendo', 'documentary'],
    },
  ],

  /* ---- Categories Config ---- */
  categories: [
    { id: 'all',             label: '🎬 ALL',          icon: '🎬' },
    { id: 'betty-boop',      label: '💋 BETTY BOOP',   icon: '💋' },
    { id: 'felix-cat',       label: '🐱 FELIX',        icon: '🐱' },
    { id: 'popeye',          label: '⚓ POPEYE',       icon: '⚓' },
    { id: 'superman',        label: '🦸 SUPERMAN',     icon: '🦸' },
    { id: 'looney-tunes',    label: '🐰 LOONEY',       icon: '🐰' },
    { id: 'woody-woodpecker',label: '🐦 WOODY',        icon: '🐦' },
    { id: 'casper',          label: '👻 CASPER',       icon: '👻' },
    { id: 'mighty-mouse',    label: '🐭 MIGHTY',       icon: '🐭' },
    { id: 'nes-gameplay',    label: '🎮 NES PLAY',     icon: '🎮' },
    { id: 'nes-speedrun',    label: '⚡ SPEEDRUN',     icon: '⚡' },
    { id: 'nes-review',      label: '⭐ REVIEWS',      icon: '⭐' },
    { id: 'nes-history',     label: '📚 HISTORY',      icon: '📚' },
    { id: 'nes-walkthrough', label: '🗺️  WALKTHROUGH', icon: '🗺️' },
  ],

  /* ---- NES Game Library (for emulator page) ---- */
  games: [
    {
      id: 'homebrew_1',
      title: 'Alter Ego',
      genre: 'Platformer',
      icon: '🎮',
      description: 'An NES homebrew platformer with unique dual character mechanics.',
      archiveId: 'AlterEgo-NES',
      romUrl: 'https://archive.org/download/AlterEgo-NES/AlterEgo.nes',
      freeware: true,
      year: 2011,
      players: 1,
    },
    {
      id: 'homebrew_2',
      title: 'Blade Buster',
      genre: 'Shooter',
      icon: '🚀',
      description: 'A vertical scrolling shooter NES homebrew game.',
      archiveId: 'BladeBuster-NES',
      romUrl: 'https://archive.org/download/BladeBuster-NES/BladeBuster.nes',
      freeware: true,
      year: 2010,
      players: 1,
    },
    {
      id: 'homebrew_3',
      title: 'Böbl',
      genre: 'Platformer',
      icon: '🫧',
      description: 'A colorful NES homebrew platform game with bubble mechanics.',
      archiveId: 'Bobl-NES',
      romUrl: 'https://archive.org/download/Bobl-NES/Bobl.nes',
      freeware: true,
      year: 2019,
      players: 1,
    },
    {
      id: 'demo_1',
      title: 'Dnes Demo',
      genre: 'Demo',
      icon: '🌈',
      description: 'A colorful NES demo showcasing graphics capabilities.',
      archiveId: 'dnes-demo',
      romUrl: 'https://archive.org/download/dnes-demo/dnes_demo.nes',
      freeware: true,
      year: 2008,
      players: 1,
    },
    {
      id: 'homebrew_4',
      title: 'Lan Master',
      genre: 'Puzzle',
      icon: '🔌',
      description: 'A network-building puzzle game for NES.',
      archiveId: 'LanMaster-NES',
      romUrl: 'https://archive.org/download/LanMaster-NES/LanMaster.nes',
      freeware: true,
      year: 2001,
      players: 2,
    },
    {
      id: 'homebrew_5',
      title: 'Super Bat Puncher Demo',
      genre: 'Platformer',
      icon: '🦇',
      description: 'A detailed NES demo showcasing impressive programming techniques.',
      archiveId: 'SuperBatPuncher',
      romUrl: 'https://archive.org/download/SuperBatPuncher/SuperBatPuncher.nes',
      freeware: true,
      year: 2011,
      players: 1,
    },
    {
      id: 'homebrew_6',
      title: 'Driar',
      genre: 'Puzzle',
      icon: '🎯',
      description: 'An NES homebrew puzzle/platformer hybrid.',
      archiveId: 'Driar-NES',
      romUrl: 'https://archive.org/download/Driar-NES/Driar.nes',
      freeware: true,
      year: 2011,
      players: 1,
    },
    {
      id: 'homebrew_7',
      title: 'Lawn Mower',
      genre: 'Action',
      icon: '🌿',
      description: 'A humorous NES action game about mowing lawns.',
      archiveId: 'LawnMower-NES',
      romUrl: 'https://archive.org/download/LawnMower-NES/LawnMower.nes',
      freeware: true,
      year: 2000,
      players: 1,
    },
    {
      id: 'homebrew_8',
      title: 'Nesert Bus',
      genre: 'Simulation',
      icon: '🚌',
      description: 'The NES port of the infamous Desert Bus experience.',
      archiveId: 'NesertBus',
      romUrl: 'https://archive.org/download/NesertBus/NesertBus.nes',
      freeware: true,
      year: 2012,
      players: 1,
    },
    {
      id: 'homebrew_9',
      title: 'Invasion of the Zombie Monsters',
      genre: 'Action',
      icon: '🧟',
      description: 'Fight off zombie hordes in this NES homebrew action game.',
      archiveId: 'InvasionZombieMonsters-NES',
      romUrl: 'https://archive.org/download/InvasionZombieMonsters-NES/InvasionZombieMonsters.nes',
      freeware: true,
      year: 2011,
      players: 1,
    },
    {
      id: 'homebrew_10',
      title: 'Falling',
      genre: 'Puzzle',
      icon: '🧩',
      description: 'A Tetris-inspired falling block puzzle game for NES.',
      archiveId: 'Falling-NES',
      romUrl: 'https://archive.org/download/Falling-NES/Falling.nes',
      freeware: true,
      year: 2010,
      players: 1,
    },
    {
      id: 'homebrew_11',
      title: 'Nova The Squirrel',
      genre: 'Platformer',
      icon: '🐿️',
      description: 'A polished NES platformer starring Nova the Squirrel.',
      archiveId: 'NovaSquirrel-NES',
      romUrl: 'https://archive.org/download/NovaSquirrel-NES/NovaSquirrel.nes',
      freeware: true,
      year: 2017,
      players: 1,
    },
  ],

  /* ---- Helper Methods ---- */
  getByCategory(category) {
    if (category === 'all') return [...this.cartoons, ...this.nesVideos];
    return [...this.cartoons, ...this.nesVideos].filter(m => m.category === category);
  },

  getById(id) {
    return [...this.cartoons, ...this.nesVideos].find(m => m.id === id);
  },

  getFeatured() {
    return [
      this.cartoons.find(c => c.id === 'superman_1'),
      this.cartoons.find(c => c.id === 'betty_1'),
      this.cartoons.find(c => c.id === 'popeye_2'),
      this.nesVideos.find(v => v.id === 'nes_yt_3'),
    ].filter(Boolean);
  },

  search(query) {
    const q = query.toLowerCase();
    return [...this.cartoons, ...this.nesVideos].filter(m =>
      m.title.toLowerCase().includes(q) ||
      (m.description && m.description.toLowerCase().includes(q)) ||
      (m.tags && m.tags.some(t => t.includes(q)))
    );
  },
};

// Export for module usage
if (typeof module !== 'undefined') module.exports = MoviesData;
